version: '3'

services:
  proxy_pool:
    container_name: proxy_pool
    image: endoffight/proxy_pool:0.6.3
    restart: always
    ports:
      - 8088:8088
      - 8089:8089
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    networks:
      - proxy-pool
    environment:
      CONFIG_CHROMEWS: chrome

  chrome:
    container_name: proxy_chrome
    image: chromedp/headless-shell:stable
    restart: always
    networks:
      - proxy-pool

networks:
  proxy-pool: